console.log("Running all test suites...");
import './test_dates';
import './test_attendance';
import './test_schedule_sync';
import './test_homework';
import './test_telegram_webapp';
import './test_samgtu_parser';
import './test_faid_schedule';
import './test_faid_attendance';
import './verify_student_ux';
import './test_ingt209_schedule';
import './test_qa_ingt209_verification';
import { runHomeworkLifecycleStressTest } from './test_homework_lifecycle_stress';
await runHomeworkLifecycleStressTest();
console.log("\n=================================================");
console.log("       ALL TEST SUITES COMPLETED SUCCESSFULLY  ");
console.log("=================================================");
